variable "prefix" {}
variable "env" {}
variable "location" {}
variable "rg_name" {}
variable "application_port" {}
variable "subnet_id" {}
variable "scaleset_image_name" {}
variable "vm_ssh_public_key_file" {}
variable "scaleset_capacity" {}
variable "scaleset_vm_custom_data_file" {}
variable "image_rg_name" {}
